/* eslint-disable */
// tslint:disable
/**
 * Hospital Management Service
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import appointments from './api/appointments'
import doctor from './api/doctor'
import user from './api/user'
import users from './api/users'
import * as t from './types'

export default function(app: Express, impl: t.ApiImplementation) {
	appointments(app, impl.appointments)
	doctor(app, impl.doctor)
	user(app, impl.user)
	users(app, impl.users)
}
