"use strict";
/* eslint-disable */
// tslint:disable
/**
 * Hospital Management Service
 *
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const appointments_1 = __importDefault(require("./api/appointments"));
const doctor_1 = __importDefault(require("./api/doctor"));
const user_1 = __importDefault(require("./api/user"));
const users_1 = __importDefault(require("./api/users"));
function default_1(app, impl) {
    (0, appointments_1.default)(app, impl.appointments);
    (0, doctor_1.default)(app, impl.doctor);
    (0, user_1.default)(app, impl.user);
    (0, users_1.default)(app, impl.users);
}
exports.default = default_1;
