/* eslint-disable */
// tslint:disable
/**
 * Hospital Management Service
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import passport from 'passport'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.UserApi) {
	app.get(
		'/user/patient_profile',
		function (req, res) {
			try {
				impl.getProfile(v.allowUndefined(v.parseString)('query.id', req.query['id'])).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiGetProfile200ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in user.getProfile', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiGetProfile404ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in user.getProfile', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}

					console.log('Unsupported response in user.getProfile', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in user.getProfile', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.put(
		'/user/update_patient',
		function (req, res) {
			try {
				impl.updatepatient(v.allowUndefined(v.parseString)('query.id', req.query['id'])).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiUpdatepatient200ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in user.updatepatient', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiUpdatepatient404ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in user.updatepatient', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}

					console.log('Unsupported response in user.updatepatient', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in user.updatepatient', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.post(
		'/users/patient_signin',
		function (req, res) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiSignInRequestFromJson('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.signIn(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiSignIn200ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in user.signIn', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiSignIn404ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in user.signIn', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 500) {
						let body: any
						try {
							body = v.modelApiSignIn500ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in user.signIn', error)
							res.status(500)
							res.send()
							return
						}

						res.status(500)
						res.send(body)
						return
					}

					console.log('Unsupported response in user.signIn', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in user.signIn', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

}
