/* eslint-disable */
// tslint:disable
/**
 * Hospital Management Service
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface DoctorApi {
	createDoctor: (request: Api.CreateDoctor | undefined) => Promise<CreateDoctorResponse>
	doctorSign: (request: Api.DoctorSignRequest | undefined) => Promise<DoctorSignResponse>
}

export type CreateDoctorResponse = CreateDoctor201Response | CreateDoctor404Response

export interface CreateDoctor201Response {
	status: 201
	body: Api.CreateDoctor201Response
	headers?: never
}

export interface CreateDoctor404Response {
	status: 404
	body: Api.CreateDoctor404Response
	headers?: never
}

export type DoctorSignResponse = DoctorSign200Response | DoctorSign404Response | DoctorSign500Response

export interface DoctorSign200Response {
	status: 200
	body: Api.DoctorSign200Response
	headers?: never
}

export interface DoctorSign404Response {
	status: 404
	body: Api.DoctorSign404Response
	headers?: never
}

export interface DoctorSign500Response {
	status: 500
	body: Api.DoctorSign500Response
	headers?: never
}

