/* eslint-disable */
// tslint:disable
/**
 * Hospital Management Service
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import passport from 'passport'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.AppointmentsApi) {
	app.post(
		'/appointment',
		function (req, res) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiCreateAppointmentFromJson('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.createAppointment(__body()).then(function (response) {
					if (response.status === 201) {
						let body: any
						try {
							body = v.modelApiCreateAppointment201ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in appointments.createAppointment', error)
							res.status(500)
							res.send()
							return
						}

						res.status(201)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiCreateAppointment404ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in appointments.createAppointment', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 500) {
						let body: any
						try {
							body = v.modelApiCreateAppointment500ResponseToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in appointments.createAppointment', error)
							res.status(500)
							res.send()
							return
						}

						res.status(500)
						res.send(body)
						return
					}

					console.log('Unsupported response in appointments.createAppointment', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in appointments.createAppointment', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

}
