/* eslint-disable */
// tslint:disable
/**
 * Hospital Management Service
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface AppointmentsApi {
	createAppointment: (request: Api.CreateAppointment | undefined) => Promise<CreateAppointmentResponse>
}

export type CreateAppointmentResponse = CreateAppointment201Response | CreateAppointment404Response | CreateAppointment500Response

export interface CreateAppointment201Response {
	status: 201
	body: Api.CreateAppointment201Response
	headers?: never
}

export interface CreateAppointment404Response {
	status: 404
	body: Api.CreateAppointment404Response
	headers?: never
}

export interface CreateAppointment500Response {
	status: 500
	body: Api.CreateAppointment500Response
	headers?: never
}

